[package]
name = "core"
version = "0.1.0"
authors = ["Aulang <aulang@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = "1.0.118"
serde_derive = "1.0.118"
structopt = "0.3.21"